version: "2.4.1"

services:
  reimbursement-app:
    image: reimbursement-api
    container_name: rApp
    restart: always
    environment:
      - DB_URL=jdbc:mysql://34.130.53.121:3306/ReimbursementAPI
#      - EMAIL_URL=http://web2:8000/path/to/post
    ports:
      - 8500:8500
    depends_on:
      - db

  email-api:
    image: email-api
    container_name: eApp
    restart: always
    environment:
      - DB_URL=jdbc:mysql://34.135.95.88:3306/ReimbursementAPI
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Ccc12345!!!
      - MYSQL_DATABASE=ReimbursementAPI
      - MYSQL_ROOT_USER=root
